services:
  - type: web
    name: nvidia-nim-proxy
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: NVIDIA_API_KEY
        value: tua-api-key-nvidia
